swagger: "2.0"
info:
  title: "Mock Dukedoms Card Service Api"
  version: "0.1.1"

paths:
  /getCardList/{gameId}:
    get:
      summary: get the card list for a given game
      x-swagger-router-controller: controllers.list_operations
      operationId: get_card_list
      tags:
        - listOperations
      parameters:
        - in: path
          name: gameId
          type: integer
          required: true
          description: id of the game for which to fetch card list
      responses:
        200:
          description: game card list found successfully
          schema:
            $ref: '#/definitions/CardList'
        404:
          description: no game found with that id

  /getCardCatalog:
    get:
      summary: return list of all possible game cards
      x-swagger-router-controller: controllers.card_info
      operationId: get_card_catalog
      tags:
        - cardInfo
      responses:
        200:
          description: card list returned successfully
          schema:
            $ref: '#/definitions/CardList'

  /getCards/{cardIds}:
    get:
      summary: get info for specified cards
      x-swagger-router-controller: controllers.card_info
      operationId: get_card_info
      tags:
        - cardInfo
      parameters:
        - in: path
          name: cardIds
          type: array
          items:
            type: string
          required: true
          description: array of card ids for which to fetch info
      responses:
        200:
          description: card info fetched successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/CardInfo'
        404:
          description: unable to find following card ids
          schema:
            type: array
            items:
              type: integer

definitions:
  CardList:
    type: object
  CardInfo:
    type: object
